# Render 部署配置文件
# 文档: https://render.com/docs/blueprint-spec

services:
  # Web 服务
  - type: web
    name: capcut-api-server
    env: python
    region: singapore  # 选择新加坡区域（离 CapCut API 服务器近）
    plan: free  # 免费套餐，可升级为 starter ($7/月) 或更高
    branch: main  # Git 分支
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT --timeout 120 server_api_render:app
    
    # 环境变量
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ADMIN_PASSWORD
        generateValue: true  # 自动生成强密码
        sync: false
      - key: API_PASSWORD
        generateValue: true  # 全局单口令（兼容 gcli2api）
        sync: false
    
    # 健康检查
    healthCheckPath: /health
    
    # 持久化磁盘（仅付费套餐可用，免费套餐请注释掉）
    # 如果使用 Starter 或更高套餐，取消下面的注释
    # disk:
    #   name: capcut-data
    #   mountPath: /opt/render/project/src
    #   sizeGB: 1
    
    # 自动部署
    autoDeploy: true


